<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Terms & Conditions - Gameonix</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      padding: 20px;
      max-width: 900px;
      margin: auto;
    }
    h1, h2, h3 {
      color: #333;
    }
    h1 {
      text-align: center;
      margin-bottom: 30px;
    }
    p {
      margin: 10px 0;
    }
    ul {
      margin: 10px 0 10px 20px;
    }
  </style>
</head>
<body>
<p><strong><span data-contrast="auto">Terms &amp; Conditions</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-contrast="auto">The terms "We" / "Us" / "Our"/ "Company" individually and collectively refer to Gameonix App and the terms "Visitor" "User" refer to the users.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">This page states the Terms and Conditions under which you (Visitor) may visit this website (Gameonix.in) &amp; App (Gameonix). Please read this page carefully. If you do not accept the Terms and Conditions stated here, we would request you to exit this site &amp; app. The business, any of its business divisions and / or its subsidiaries, associate companies or subsidiaries to subsidiaries or such other investment companies (in India or abroad) reserve their respective rights to revise these Terms and Conditions at any time by updating this posting. You should visit this page periodically to re-appraise yourself of the Terms and Conditions, because they are binding on all users of this Website &amp; app.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Will these Terms ever change?</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-contrast="auto">We are constantly trying to improve our Services, so these Terms may need to change along with the Services. We reserve the right to change the Terms at any time, but if we do, we will bring it to your attention by placing a notice on the Gameonix website, by sending you an email, and/or by some other means.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">If you don&rsquo;t agree with the new Terms, you are free to reject them; unfortunately, that means you will no longer be able to use the Services. If you use the Services in any way after a change to the Terms is effective, that means you agree to all of the changes.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">Except for changes by us as described here, no other amendment or modification of these Terms will be effective unless in writing and signed by both you and us.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">What about my privacy?</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-contrast="auto">Gameonix takes the privacy of its users very seriously. For the current Gameonix Privacy Policy, please check our Privacy and Policy page.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">The Children&rsquo;s Online Privacy Protection Act (&ldquo;COPPA&rdquo;) requires that online service providers obtain parental consent before they knowingly collect personally identifiable information online from children who are under 13, and other applicable privacy laws place certain restrictions on collecting personally identifiable information from children under 16. We do not knowingly collect or solicit personally identifiable information from children under 16; if you are a child under 16, please do not attempt to register for the Services or send any personal information about yourself to us. If we notice that we have collected personal information from a child under 16, we will delete that information as soon as possible. If you believe that a child under 16 may have provided us personal information, please contact us at </span><a href="mailto:support@gameonix.in"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">support@gameonix.in</span></span></a><span data-contrast="auto"> .</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">About Tournaments</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-contrast="auto">The tournaments that are held using the Gameonix Platform will be organized and operated by unaffiliated third-party organizers (&ldquo;Organizers&rdquo;) in accordance with the tournament rules in place for the individual tournaments. Users may participate in a tournament after confirming their adherence to the specific tournament rules.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">The Organizers shall take any action that they consider appropriate, such as correction, addition, change, suspension, cancellation, termination, etc., of the contents of the Services (including an on-going event) for any reason. For clarity, Gameonix does not run or sponsor individual tournaments.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">About Gameonix Promotions</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-contrast="auto">Gameonix may sponsor promotions related to the above tournaments which will be run in accordance with the applicable promotion rules as published by Gameonix for each promotion.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">About Prizes</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-contrast="auto">Gameonix may provide prizes to users as determined in the promotion rules. The promotion rules may provide requirements for claiming prizes such as requiring verification of identity, a limited period of time for the user to claim the promotion prize and/or other requirements and restrictions.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">ALL POTENTIAL WINNERS ARE SUBJECT TO VERIFICATION BY GAMEONIX. GAMEONIX&rsquo;S DECISIONS AS TO THE ADMINISTRATION AND OPERATION OF THE PROMOTION, ANY CHANGES TO THE OFFICIAL RULES, AND THE SELECTION OF POTENTIAL PRIZE WINNERS ARE FINAL AND BINDING AND NOT SUBJECT TO CHALLENGE OR APPEAL.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">About Gameonix NFTs</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-contrast="auto">Gameonix may make available NFTs (non-fungible tokens) that you may acquire and use on the Platform as part of your enjoyment and use of the Services. Terms regarding the creation, purchase and use of NFTs can be found on the NFT page.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">What are my rights in Gameonix?</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-contrast="auto">The materials displayed or performed or available on or through the Services, including, but not limited to, text, graphics, data, articles, photos, images, illustrations, User Submissions, and so forth (all of the foregoing, the &ldquo;Content&rdquo;) are owned by Gameonix or its licensors and are protected by copyright and/or other intellectual property laws. You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, and you won&rsquo;t use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell or otherwise exploit for any purpose any Content not owned by you,&nbsp;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<ol>
<li data-leveltext="(%1)" data-font="" data-listid="1" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:1080,&quot;335559991&quot;:720,&quot;469769242&quot;:[65533,2],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;(%1)&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="1" data-aria-level="1"><span data-contrast="auto">without the prior consent of the owner of that Content or&nbsp;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
</ol>
<ol>
<li data-leveltext="(%1)" data-font="" data-listid="1" data-list-defn-props="{&quot;335552541&quot;:0,&quot;335559685&quot;:1080,&quot;335559991&quot;:720,&quot;469769242&quot;:[65533,2],&quot;469777803&quot;:&quot;left&quot;,&quot;469777804&quot;:&quot;(%1)&quot;,&quot;469777815&quot;:&quot;hybridMultilevel&quot;}" data-aria-posinset="2" data-aria-level="1"><span data-contrast="auto">in a way that violates someone else&rsquo;s (including Gameonix&rsquo;s) rights.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
</ol>
<p><span data-contrast="auto">You understand that Gameonix owns the Services. You won&rsquo;t modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section), create derivative works based on, or otherwise exploit any of the Services.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">The Services may allow you to copy or download certain Content; please remember that just because this functionality exists, doesn&rsquo;t mean that all the restrictions above don&rsquo;t apply &ndash; they do!</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Will Gameonix ever change the Services?</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-contrast="auto">We&rsquo;re always trying to improve the Services, so they may change over time. We may suspend or discontinue any part of the Services, or we may introduce new features or impose limits on certain features or restrict access to parts or all of the Services. We&rsquo;ll try to give you notice when we make a material change to the Services that would adversely affect you, but this isn&rsquo;t always practical. Similarly, we reserve the right to remove any Content from the Services at any time, for any reason (including, but not limited to, if someone alleges you contributed that Content in violation of these Terms), in our sole discretion, and without notice.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Does Gameonix cost anything?</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-contrast="auto">Many of our Services are currently free. We reserve the right to require payment of fees for certain or all Services. To the extent that certain of our Services may be subject to payments now or in the future (the &ldquo;Paid Services&rdquo;), the following terms apply:</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Billing:</span></strong><span data-ccp-props="{}">&nbsp;</span></p>
<p><span data-contrast="auto">We use a third-party payment processor, such as Apple App Store or Google Play Store or any other Payment Gateway, (the &ldquo;Payment Processor&rdquo;) to bill you through a payment account linked to your Gameonix account on the Services (your &ldquo;Billing Account&rdquo;) for use of the Paid Services. The processing of payments will be subject to the terms, conditions and privacy policies of the Payment Processor in addition to these Terms. We are not responsible for errors by the Payment Processor. By choosing to use Paid Services, you agree to pay us, through the Payment Processor, all charges at the prices then in effect for any use of such Paid Services in accordance with the applicable payment terms and you authorize us, through the Payment Processor, to charge your chosen payment provider or source (your &ldquo;Payment Method&rdquo;). You agree to make payment using that selected Payment Method.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">If the Payment Processor identifies or we otherwise believe that your transaction may pose an unacceptable level of risk, that you have breached these Terms, or that your account has been compromised, they may take various actions to avoid liability and reduce potential fraud and disputes.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Payment Method:</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">The terms of your payment will be based on your Payment Method and may be determined by agreements between you and the financial institution, credit card issuer or other provider of your chosen Payment Method. If we, through the Payment Processor, do not receive payment from you, you agree to pay all amounts due on your Billing Account upon demand.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Current Information Required:</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">You must provide current, complete and accurate information for your billing account to the Payment Processor.  You must promptly update all information to keep your billing account current, complete and accurate (such as a change in billing address, credit card number, or credit card expiration date) through your Gameonix account, and you must promptly notify our payment processor if your payment method is canceled (e.g., for loss or theft) or if you become aware of a potential breach of security, such as the unauthorized disclosure or use of your user&rsquo;s name or password.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">No Refund or Cancellation:</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">Except as required by Google Play Store or Apple App Store, all purchases of Paid Services are non-refundable and are non- cancellable once purchased.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto"> </span><strong><span data-contrast="auto">What are Gameonix Coins?</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">Gameonix Coins are part of our Services. Please refer to the Gameonix Coins page for more details about the Gameonix Coins governed by these Terms.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Paid Coins:</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">You may purchase Gameonix Coins (&ldquo;Coins&rdquo;) through the Coin Store.  Coins you purchase will be credited to your account within 24 hours. The value that you paid in the local currency for your Coins is a prepayment only for the redemption of items available for redemption on our Platform via the Services. No credit card, credit line, overdraft protection or deposit account is associated with your Coins account.  No interest, dividends or any other earnings on funds deposited in your account for Coins will accrue or be paid or credited to you by Gameonix. The value associated with your Coins is not insured and cannot be redeemed for cash or cash equivalents. You may not transfer Coins you purchase to another individual or account in any fashion.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Free Coins:</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">We endeavor to reward you for being a loyal user of our Services through our rewards programs. We may, but have no obligation to, grant you Coins free of charge (such coins, &ldquo;Free Coins&rdquo;) in accordance with our rewards program, such as Quick Duels. Please refer to the rewards page(s), such as the Quick Duels page, for more details about the programs. You can redeem the Free Coins you earned for items available for redemption on our Platform via the Services.  A Free Coin is not cash or a cash equivalent and cannot be redeemed for cash or cash equivalents. You may not transfer your Free Coins to another individual or account in any fashion.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">We reserve the right to change, modify and/or eliminate Free Coins and the terms applicable thereto at any time upon notice to you (which may be provided through the Services or by modifying these Terms).  We reserve the right to terminate your participation in the rewards program if we determine in our reasonable discretion that you have violated these Terms or that the use of your Free Coin is unauthorized, deceptive, fraudulent or otherwise unlawful.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Purchase of Coins:</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">You can pay for Coins by using a payment method accepted at the Gameonix application checkout, Holders of any Coins are not sent statements of itemized transactions from us. You can check the balance of your Coins through the Services. We reserve the right not to accept or otherwise limit use of any Coins if we reasonably believe that the use is unauthorized, fraudulent, in violation of these Terms or otherwise unlawful.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">No Refund or Cancellation of Coin Purchases:</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">Except as required by Google Play Store or Apple App Store, all purchases of Coins are non-refundable and are non-cancellable once purchased. In the event you dispute a Coin purchase you make or attempt to dispute or chargeback any charge for the Coins with your bank or card provider, we reserve the right to submit your transaction or redemption history as evidence of funds being used to the disputing bank.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">We do not charge any fees for the opening, activation or use of your Coins account. The value in your Coins account has no expiration date.  Please note, however, that if you have not redeemed the value in your Coins for a certain period of time after such value was added, applicable law may require us to remit such value to the state in which the purchasing user was or is located, or the state in which Gameonix is incorporated. This time period will vary from state to state; it may be as short as one year. Accordingly, please remember to use your Coins in a timely manner. You release us from any liability in connection with our compliance with laws applicable in this regard.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">What are NFTs?</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">NFTs (or non-fungible tokens) are digital tokens that link to specific artwork or other content. On the Gameonix Platform, NFTs can link to Content or images of a specific user, gamer, personality or from a particular game available on the Platform. Users can create or &ldquo;mint&rdquo; their own NFTs by going to the NFT user dashboard.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">On the dashboard, users can use templates and design tools to create and upload artwork that will be linked to the NFT using Content that the user owns or has rights to publish, for example the user&rsquo;s profile image or avatar. Game developers and publishers can use their game Content to create NFTs based on in-game characters and other game images, for users to enjoy as part of their Gameonix experience.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">In accordance with your general representation above, when you create and display and/or sell your NFT on the Platform, you are responsible for ensuring that you have all necessary rights and permissions for the use, display and distribution of the NFT Content, including consent to display the Likeness of any person visible in the Content. For example, you should not create an NFT based on your favorite game characters unless you are the developer or publisher of the game.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">NFT creators will be able to make their NFTs available for purchase by other users on home pages and Club pages on the Platform using Gameonix Coins. NFT creators can set the price and other attributes for their NFT on the dashboard before publishing the NFT. NFT creators will receive a credit in Coins to their Gameonix accounts from such purchases.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">NFT purchasers can display their purchased NFTs on their Home, Club or Profile page on the Platform. However, purchase of an NFT does not convey any copyright or other ownership rights in the Content linked to the NFT.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">When it becomes available, NFTs may be traded between users via an NFT marketplace on the Platform. NFTs may not be traded, sold or exchanged outside the Platform.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Use of Content:</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">All logos, brands, marks headings, labels, names, signatures, numerals, shapes or any combinations thereof, appearing in this site, except as otherwise noted, are properties either owned, or used under license, by the business and / or its associate entities who feature on this Website. The use of these properties or any other content on this site, except as provided in these terms and conditions or in the site content, is strictly prohibited.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">You may not sell or modify the content of this Website or reproduce, display, publicly perform, distribute, or otherwise use the materials in any way for any public or commercial purpose without the respective organizations or entity&rsquo;s written permission.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Acceptable Website Use:</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">(A)Security Rules</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">Visitors are prohibited from violating or attempting to violate the security of the Website, App, including, without limitation,</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">(1) accessing data not intended for such user or logging into a server or account which the user is not authorized to access,</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">(2) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization,</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">(3) attempting to interfere with service to any user, host or network, including, without limitation, via means of submitting a virus or "Trojan horse" to the Website, overloading, "flooding", "mail bombing" or "crashing", or</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">(4) sending unsolicited electronic mail, including promotions and/or advertising of products or services. Violations of system or network security may result in civil or criminal liability. The business and / or its associate entities will have the right to investigate occurrences that they suspect as involving such violations and will have the right to involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">(B) General Rules</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">Visitors may not use the Web Site in order to transmit, distribute, store or destroy material</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">(a) that could constitute or encourage conduct that would be considered a criminal offence or violate any applicable law or regulation,</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">(b) in a manner that will infringe the copyright, trademark, trade secret or other intellectual property rights of others or violate the privacy or publicity of other personal rights of others, or</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">(c) that is libelous, defamatory, pornographic, profane, obscene, threatening, abusive or hateful.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Indemnity:</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">The User unilaterally agree to indemnify and hold harmless, without objection, the Company, its officers, directors, employees and agents from and against any claims, actions and/or demands and/or liabilities and/or losses and/or damages whatsoever arising from or resulting from their use of Gameonix.com or their breach of the terms.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Liability:</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">User agrees that neither Company nor its group companies, directors, officers or employee shall be liable for any direct or/and indirect or/and incidental or/and special or/and consequential or/and exemplary damages, resulting from the use or/and the inability to use the service or/and for cost of procurement of substitute goods or/and services or resulting from any goods or/and data or/and information or/and services purchased or/and obtained or/and messages received or/and transactions entered into through or/and from the service or/and resulting from unauthorized access to or/and alteration of user's transmissions or/and data or/and arising from any other matter relating to the service, including but not limited to, damages for loss of profits or/and use or/and data or other intangible, even if Company has been advised of the possibility of such damages.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">User further agrees that Company shall not be liable for any damages arising from interruption, suspension or termination of service, including but not limited to director/and indirect or/and incidental or/and special consequential or/and exemplary damages, whether such interruption or/and suspension or/and termination was justified or not, negligent or intentional, inadvertent or advertent.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">User agrees that Company shall not be responsible or liable to user, or anyone, for the statements or conduct of any third party of the service. In sum, in no event shall Company's total liability to the User for all damages or/and losses or/and causes of action exceed the amount paid by the User to Company, if any, that is related to the cause of action.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><strong><span data-contrast="auto">Disclaimer of Consequential Damages:</span></strong><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">In no event shall Company or any parties, organizations or entities associated with the corporate brand name us or otherwise, mentioned at this Website be liable for any damages whatsoever (including, without limitations, incidental and consequential damages, lost profits, or damage to computer hardware or loss of data information or business interruption) resulting from the use or inability to use the Website and the Website material, whether based on warranty, contract, tort, or any other legal theory, and whether or not, such organization or entities were advised of the possibility of such damages.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">Softpin: Does not include manuals, installation CDs, box, physical card or other physical elements. A Buyer will be able to view his code(s) in his order page after his successful purchase. Refund on pre-order Item may be available until two (2) weeks prior to product release. This does not apply to pre-order of CD Game Key. A successful purchase by a Buyer of any pre-order Item or Item made available for sale on the Platform indicates that all information such Buyer has entered is accurate and correct. Any purchase of pre-order Item, CD Key, Time Card, Expansion, Game Point, Prepaid Card, Trial/Beta/Item Code, Game Key on the Platform are non refundable, non-transferable, and not exchangeable once sold, unless otherwise agreed in writing by GAMEONIX. GAMEONIX reserves the right to amend any of the terms and conditions above without prior notice.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<p><span data-contrast="auto">Direct Top Up: Please read the product description thoroughly and confirm that the game name, server, account name and the amount purchased are correct. GAMEONIX assumes no liability for wrong purchases made by the customer due to negligence and/or false or wrong information provided, which may result in damages and losses. By purchasing any Items from GAMEONIX on the Platform, the Buyer understands, acknowledges and accepts this release of liability. If you encounter any difficulties, please do not hesitate to contact our customer service team for further assistance.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>

</body>
</html>
